- name: variables from PLAY level
  hosts: localhost
  var:
    Course: "Ansible"
    Trainer: "siva"
    Duration: "10hrs"
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "hi, i am learning {{Course}}, Trainer is {{Trainer}}, duration is {{Duration}}
