- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: print persons
    ansible.builtin.package:
      name: {{item}}
      state: present
    ansible.builtin.debug:
      msg: "HELLO {{item}}"
    loop: 
    - git
    - mysql
    - postfix  